import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import '../styles/reset.css'
import '../styles/globals.css'

const notoSansKR = Noto_Sans_KR({
  weight: ['300', '500', '700', '900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Billionaire Board',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={`${notoSansKR.className} antialiased`}>{children}</body>
    </html>
  )
}
